project_name: goreleaser-action-test
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X example.com/goreleaser-action-test/version.ProviderVersion={{.Version}}
