project_name: goreleaser-action-test
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X version.ProviderVersion={{.Version}} -X main.version={{.Version}} -X main.commit={{.Commit}}"
